version: '3.8'

services:
  teamtrip-dashboard:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: dashbord-app
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - ../:/usr/src/app

    command: |
      sh -c "
        npm install &&
        npm run preview
      "